#!/usr/bin/env python3
"""Generate crawlable category, brand, and product HTML plus sitemaps."""
from __future__ import annotations

import json
import re
import shutil
from collections import Counter, defaultdict
from html import escape
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = "https://kakobuysheetqc.com"
MARKER = "generated by scripts/build_seo_pages.py"
AFF = "9v88f"
TODAY = "2026-09-18"
ASSETS = """  <link rel="icon" href="/img/favicon.png" type="image/png" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;600;700&family=Montserrat:ital,wght@0,700;0,800;1,700;1,800&family=Nunito:wght@400;500&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/css/style.css" />
  <script src="/js/analytics.js"></script>"""
SCRIPTS = """  <script src="/js/data.js?v=14"></script>
  <script src="/js/catalog.js?v=7"></script>
  <script src="/js/ui.js?v=14"></script>
  <script src="/js/pages.js?v=14"></script>"""

CAT_LABELS = {
    "shoes": "Shoes",
    "t-shirts": "T-Shirts",
    "hoodies": "Hoodies / Sweaters",
    "jackets": "Jackets",
    "pants": "Pants / Shorts",
    "sets": "Sets",
    "jersey": "Jerseys",
    "underwear": "Underwear",
    "headwear": "Headwear",
    "glasses": "Glasses",
    "watches": "Watches",
    "perfume": "Perfume",
    "accessories": "Accessories",
    "bricks": "Building Blocks",
    "other": "Other Stuff",
}
CAT_INTRO = {
    "shoes": "Sneakers, boots and court shoes with USD prices, QC flags and a working Kakobuy link on every pair.",
    "t-shirts": "Graphic tees and basics indexed from Weidian, Taobao and 1688 — open a card, then check out on Kakobuy.",
    "hoodies": "Hoodies and sweaters for haul season. Preview QC on the find, then order through Kakobuy.",
    "jackets": "Jackets and outerwear with listing photos up front so you are not scrolling a frozen sheet.",
    "pants": "Pants and shorts grouped in one grid, priced in USD, with direct Kakobuy checkout links.",
    "sets": "Matching sets and tracksuits. Compare the listing here, then buy on Kakobuy.",
    "jersey": "Football, basketball and retro jerseys with QC flags where we have them.",
    "underwear": "Underwear and basics from the Kakobuy Spreadsheet catalog.",
    "headwear": "Caps, beanies and hats with photos and Kakobuy links already attached.",
    "glasses": "Sunglasses and frames. Check the listing photos here, then open Kakobuy.",
    "watches": "Watch finds with USD pricing and a Kakobuy link on every card.",
    "perfume": "Fragrance listings from the Kakobuy Spreadsheet catalog.",
    "accessories": "Belts, wallets, jewelry and small goods — browse here, order on Kakobuy.",
    "bricks": "Building-block sets indexed for Kakobuy shoppers.",
    "other": "Finds that do not sit in a single apparel lane, still with photos and working links.",
}

SKIP_BRAND = {"find", ""}


def load_products() -> list[dict]:
    raw = (ROOT / "js" / "catalog.js").read_text(encoding="utf-8")
    start = raw.index("KF.products = ") + len("KF.products = ")
    products, _ = json.JSONDecoder().raw_decode(raw[start:])
    skip = re.compile(r"sock|suitcase|luggage", re.I)
    extra_set = re.compile(r"tracksuit|track\s*suit|sportsuit|\bsuit\b", re.I)
    for p in products:
        title = str(p.get("title") or "")
        if p.get("category") == "sets" or skip.search(title) or not extra_set.search(title):
            continue
        extra = list(p.get("categories") or [])
        if "sets" not in extra:
            extra.append("sets")
        p["categories"] = extra
    return products


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", (text or "").lower())
    s = re.sub(r"^-+|-+$", "", s)
    s = re.sub(r"-+", "-", s)
    return s[:60]


def item_id(p: dict) -> str:
    return re.sub(r"^p-", "", str(p.get("id") or ""), count=1)


def item_slug(p: dict) -> str:
    base = slugify(str(p.get("title") or ""))
    num = item_id(p)
    return f"{base}-{num}" if base else num


def asset(path: str) -> str:
    s = path or ""
    if not s or s.startswith("http") or s.startswith("/"):
        return s
    return "/" + s.lstrip("./")


def abs_url(path: str) -> str:
    return ORIGIN + path


def kakobuy_url(source_url: str) -> str:
    url = source_url or ""
    weidian = re.search(r"itemID=(\d+)", url, re.I)
    if weidian or "weidian.com" in url.lower():
        if weidian:
            return (
                "https://www.kakobuy.com/item/details?url="
                f"https%3A%2F%2Fweidian.com%2Fitem.html%3FitemID%3D{weidian.group(1)}"
                f"&affcode={AFF}"
            )
    return f"https://www.kakobuy.com/item/details?url={quote(url, safe='')}&affcode={AFF}"


def in_category(p: dict, slug: str) -> bool:
    cats = [p.get("category")] + list(p.get("categories") or [])
    return slug in {c for c in cats if c}


def wipe_generated(dir_path: Path) -> None:
    index = dir_path / "index.html"
    if index.exists() and MARKER in index.read_text(encoding="utf-8", errors="ignore"):
        shutil.rmtree(dir_path)


def head(title: str, description: str, canonical: str, extra: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <!-- {MARKER} -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(title)}</title>
  <meta name="description" content="{escape(description)}" />
  <meta name="robots" content="index, follow, max-image-preview:large" />
  <link rel="canonical" href="{escape(canonical)}" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="{escape(title)}" />
  <meta property="og:description" content="{escape(description)}" />
  <meta property="og:url" content="{escape(canonical)}" />
  <meta property="og:image" content="{ORIGIN}/img/logo.png" />
{extra}{ASSETS}
</head>
"""


def product_card(p: dict) -> str:
    return (
        f'<a class="product-card" href="/item/{item_slug(p)}/" data-id="{escape(str(p["id"]))}">'
        f'<div class="thumb"><img src="{escape(asset(p.get("image") or ""))}" alt="{escape(p.get("title") or "")}" loading="lazy" decoding="async" /></div>'
        f'<h3>{escape(p.get("title") or "")}</h3>'
        f'<b>${float(p.get("price") or 0):.2f}</b></a>'
    )


def write(path: Path, html: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")


def shop_page(title: str, description: str, canonical: str, h1: str, intro: str, items: list[dict], body_attrs: str) -> str:
    cards = "\n      ".join(product_card(p) for p in items[:48])
    return (
        head(title, description, canonical)
        + f'<body {body_attrs}>\n'
        + f"""  <main class="wrap catalog">
    <div class="catalog-intro">
      <h1>{escape(h1)}</h1>
      <p>{escape(intro)}</p>
    </div>
    <div class="catalog-top">
      <p id="shop-count">Showing {min(48, len(items))} of {len(items)} results</p>
      <select id="sort">
        <option value="latest">Default sorting</option>
        <option value="popular">Sort by popularity</option>
        <option value="rating">Sort by average rating</option>
        <option value="price-asc">Sort by price: low to high</option>
        <option value="price-desc">Sort by price: high to low</option>
      </select>
    </div>
    <div class="product-grid" id="product-grid">
      {cards}
    </div>
    <nav class="pager" id="pager"></nav>
  </main>
{SCRIPTS}
</body>
</html>
"""
    )


def item_page(p: dict, related: list[dict]) -> str:
    slug = item_slug(p)
    path = f"/item/{slug}/"
    canonical = abs_url(path)
    title = f'{p.get("title") or "Find"} — Kakobuy Spreadsheet'
    price = float(p.get("price") or 0)
    cat = str(p.get("category") or "")
    label = CAT_LABELS.get(cat, cat)
    image = abs_url(asset(p.get("image") or "img/logo.png"))
    desc = (
        f'{p.get("title")} on the Kakobuy Spreadsheet. {label} find from {p.get("source") or "Weidian"}, '
        f"listed at ${price:.2f}. Preview QC photos here, then open Kakobuy to order."
    )
    buy = kakobuy_url(str(p.get("sourceUrl") or ""))
    qc = "QC photos on this find" if p.get("qc") else "No QC flag yet"
    ld = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": p.get("title"),
        "image": image,
        "description": desc,
        "brand": {"@type": "Brand", "name": p.get("collection") or "Kakobuy Spreadsheet"},
        "offers": {
            "@type": "Offer",
            "price": f"{price:.2f}",
            "priceCurrency": "USD",
            "availability": "https://schema.org/InStock",
            "url": canonical,
        },
    }
    extra = f'  <script type="application/ld+json">{json.dumps(ld, ensure_ascii=False)}</script>\n'
    rel = "\n        ".join(product_card(r) for r in related[:6])
    img = asset(p.get("image") or "")
    return (
        head(title, desc, canonical, extra)
        + f'<body data-page="item" data-item-id="{escape(str(p["id"]))}" data-cat="{escape(cat)}">\n'
        + f"""  <main class="wrap item-page">
    <div class="item-bar">
      <nav class="crumbs" id="crumbs">
        <a href="/">Home</a><span>/</span>
        <a href="/finds/">Shop</a><span>/</span>
        <a href="/{escape(cat)}/">{escape(label)}</a><span>/</span>
        <span>{escape(p.get("title") or "")}</span>
      </nav>
      <div class="item-switch" id="item-switch"></div>
    </div>
    <div class="item-layout">
      <div class="gallery">
        <div class="thumbs" id="thumbs"></div>
        <div class="main-stage">
          <button type="button" class="gal-arrow gal-prev" id="gal-prev" aria-label="Previous photo">‹</button>
          <div class="main" id="item-stage">
            <img id="item-main" src="{escape(img)}" alt="{escape(p.get("title") or "")}" />
          </div>
          <button type="button" class="gal-arrow gal-next" id="gal-next" aria-label="Next photo">›</button>
          <button type="button" class="gal-zoom" id="gal-zoom" aria-label="Zoom photo">
            <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8">
              <path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5"/>
            </svg>
          </button>
        </div>
      </div>
      <div class="item-info">
        <h1 id="item-title">{escape(p.get("title") or "")}</h1>
        <div class="price" id="item-price">${price:.2f}</div>
        <p class="item-rating" id="item-rating">{escape(qc)} · {escape(str(p.get("source") or ""))}</p>
        <a class="btn btn-buy" id="buy-link" href="{escape(buy)}" target="_blank" rel="noopener">Buy on Kakobuy</a>
        <p class="item-seo-note">{escape(desc)}</p>
      </div>
    </div>
  </main>
  <div class="zoom-layer" id="zoom-layer">
    <button type="button" class="zoom-close" id="zoom-close" aria-label="Close zoom">×</button>
    <img id="zoom-img" alt="" />
  </div>
  <section class="section">
    <div class="wrap">
      <h2>More in this category</h2>
      <div class="product-grid" id="related-grid" style="margin-top:16px">{rel}</div>
    </div>
  </section>
  <section class="section reviews" id="reviews">
    <div class="wrap">
      <h2>Customer Review · <span id="review-count">0</span></h2>
      <div class="review-list" id="review-list"></div>
      <form class="review-form" id="review-form">
        <label><span>Your review <em>*</em></span><textarea name="text" required rows="6"></textarea></label>
        <label><span>Name</span><input name="name" required autocomplete="name" /></label>
        <label><span>Email</span><input name="email" type="email" required autocomplete="email" /></label>
        <button class="btn btn-solid" type="submit">Post comment</button>
      </form>
    </div>
  </section>
{SCRIPTS}
</body>
</html>
"""
    )


def sitemap_xml(urls: list[tuple[str, str, str]]) -> str:
    body = "\n".join(
        f"  <url><loc>{escape(loc)}</loc><lastmod>{lastmod}</lastmod><changefreq>{freq}</changefreq></url>"
        for loc, lastmod, freq in urls
    )
    return '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n"


def main() -> None:
    products = load_products()
    by_cat = defaultdict(list)
    by_brand = defaultdict(list)
    for p in products:
        seen = set()
        for slug in [p.get("category"), *(p.get("categories") or [])]:
            if slug and slug not in seen:
                by_cat[slug].append(p)
                seen.add(slug)
        brand = str(p.get("collection") or "").strip()
        if brand.lower() not in SKIP_BRAND:
            by_brand[brand].append(p)

    reserved = {"img", "js", "css", "scripts", "item", "brands", "finds"}
    for slug in list(CAT_LABELS):
        if slug in reserved:
            continue
        wipe_generated(ROOT / slug)
    wipe_generated(ROOT / "finds")
    wipe_generated(ROOT / "brands")
    item_root = ROOT / "item"
    if item_root.exists():
        shutil.rmtree(item_root)

    finds = products
    write(
        ROOT / "finds" / "index.html",
        shop_page(
            "All finds on Kakobuy Spreadsheet",
            f"Browse {len(finds)} Kakobuy Spreadsheet finds with USD prices, QC flags and direct Kakobuy links.",
            abs_url("/finds/"),
            "All Kakobuy Spreadsheet finds",
            "The full catalog in one grid — newest first, priced in USD, each card opening on Kakobuy.",
            finds,
            'data-page="shop"',
        ),
    )

    for slug, label in CAT_LABELS.items():
        items = by_cat.get(slug, [])
        intro = CAT_INTRO.get(slug, f"{label} finds on the Kakobuy Spreadsheet.")
        write(
            ROOT / slug / "index.html",
            shop_page(
                f"{label} on Kakobuy Spreadsheet",
                f"Browse {len(items)} {label.lower()} finds on the Kakobuy Spreadsheet — USD prices, QC flags, and Kakobuy links.",
                abs_url(f"/{slug}/"),
                f"{label} on Kakobuy Spreadsheet",
                intro,
                items,
                f'data-page="shop" data-cat="{slug}"',
            ),
        )

    brand_names = sorted(
        ((name, items) for name, items in by_brand.items() if len(items) >= 5),
        key=lambda kv: (-len(kv[1]), kv[0].lower()),
    )
    brand_cards = "\n      ".join(
        f'<a class="cat-card" href="/brands/{slugify(name)}/"><span class="cat-name">{escape(name)}</span><small>{len(items)} finds</small></a>'
        for name, items in brand_names
    )
    write(
        ROOT / "brands" / "index.html",
        head(
            "Brands on Kakobuy Spreadsheet",
            "Browse Kakobuy Spreadsheet finds by brand: Nike, Jordan, Chrome Hearts and more.",
            abs_url("/brands/"),
        )
        + f"""<body data-page="brands">
  <main class="wrap catalog">
    <div class="catalog-intro">
      <h1>Brands on Kakobuy Spreadsheet</h1>
      <p>Jump into a brand grid instead of searching a 15,000-row sheet. Every card still opens on Kakobuy.</p>
    </div>
    <div class="cat-grid" id="brand-grid">
      {brand_cards}
    </div>
  </main>
{SCRIPTS}
</body>
</html>
""",
    )
    for name, items in brand_names:
        bslug = slugify(name)
        write(
            ROOT / "brands" / bslug / "index.html",
            shop_page(
                f"{name} on Kakobuy Spreadsheet",
                f"Browse {len(items)} {name} finds on the Kakobuy Spreadsheet with USD prices and Kakobuy links.",
                abs_url(f"/brands/{bslug}/"),
                f"{name} on Kakobuy Spreadsheet",
                f"{name} listings from Weidian, Taobao and 1688. Preview photos here, then order on Kakobuy.",
                items,
                f'data-page="shop" data-brand="{bslug}"',
            ),
        )

    related_map = defaultdict(list)
    for p in products:
        related_map[p.get("category")].append(p)
    slugs = {}
    for p in products:
        slug = item_slug(p)
        slugs[str(p["id"])] = slug
        related = [x for x in related_map[p.get("category")] if x["id"] != p["id"]]
        write(ROOT / "item" / slug / "index.html", item_page(p, related))

    (ROOT / "js" / "slugs.js").write_text(
        "window.KF_SLUGS = " + json.dumps(slugs, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )

    page_urls = [
        (abs_url("/"), TODAY, "daily"),
        (abs_url("/finds/"), TODAY, "daily"),
        (abs_url("/brands/"), TODAY, "weekly"),
        (abs_url("/guides.html"), TODAY, "weekly"),
        (abs_url("/about.html"), TODAY, "monthly"),
    ]
    page_urls += [(abs_url(f"/{slug}/"), TODAY, "daily") for slug in CAT_LABELS]
    page_urls += [(abs_url(f"/brands/{slugify(name)}/"), TODAY, "weekly") for name, _ in brand_names]
    product_urls = [(abs_url(f"/item/{slug}/"), TODAY, "weekly") for slug in slugs.values()]
    write(ROOT / "sitemap-pages.xml", sitemap_xml(page_urls))

    chunk_size = 200
    sm_dir = ROOT / "sitemaps"
    if sm_dir.exists():
        shutil.rmtree(sm_dir)
    sm_dir.mkdir()
    for old in ROOT.glob("sitemap-products*.xml"):
        old.unlink()
    product_sitemaps = []
    for i in range(0, len(product_urls), chunk_size):
        n = i // chunk_size + 1
        name = f"{n:02d}.xml"
        write(sm_dir / name, sitemap_xml(product_urls[i : i + chunk_size]))
        product_sitemaps.append("sitemaps/" + name)

    index_body = "\n".join(
        f"  <sitemap><loc>{abs_url('/' + name)}</loc><lastmod>{TODAY}</lastmod></sitemap>"
        for name in ["sitemap-pages.xml", *product_sitemaps]
    )
    index_xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + index_body
        + "\n</sitemapindex>\n"
    )
    write(ROOT / "sitemap-index.xml", index_xml)
    write(ROOT / "sitemap.xml", index_xml)
    print(
        f"wrote {len(products)} item pages, {len(CAT_LABELS)} categories, "
        f"{len(brand_names)} brands, {len(product_urls)} product URLs in {len(product_sitemaps)} sitemaps"
    )


if __name__ == "__main__":
    main()
